# Site settings
title: Mustafa Aydin
description: Personal Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://mustafa.tc" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: MUSTAFA AYDIN
#user_description: 
#user_title: Software Developer
email: anon@anon.com
linkedin: https://www.linkedin.com/in/mustafayd/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
